const combinedFields = [
    { field_name: "building", input_type: "text" },
    { field_name: "block", input_type: "text" },
    { field_name: "area", input_type: "text" },
    { field_name: "city", input_type: "text" },
    { field_name: "district", input_type: "text" },
    { field_name: "region", input_type: "text" },
    { field_name: "pin_code", input_type: "text" },
    { field_name: "country", input_type: "select", options: ["India", "USA", "UK"] },
    { field_name: "landmark", input_type: "text" },
    { field_name: "floor_number", input_type: "number" },
    { field_name: "apartment_name", input_type: "text" },
    { field_name: "blood_group", input_type: "select", options: ["O+", "A+", "B+", "AB+"] },
    { field_name: "allergies", input_type: "text" },
    { field_name: "chronic_conditions", input_type: "text" },
    { field_name: "medical_history", input_type: "text" },
    { field_name: "medications", input_type: "text" },
    { field_name: "doctor_name", input_type: "text" },
    { field_name: "doctor_contact", input_type: "text" },
    { field_name: "emergency_contact", input_type: "nested" },
    { field_name: "health_insurance_provider", input_type: "text" },
    { field_name: "insurance_policy_number", input_type: "text" },
    { field_name: "emergency_medical_conditions", input_type: "text" },
    { field_name: "school_name", input_type: "text" },
    { field_name: "degree_qualification", input_type: "text" },
    { field_name: "year_of_completion", input_type: "number" },
    { field_name: "major", input_type: "text" },
    { field_name: "grade_percentage", input_type: "text" },
    { field_name: "extracurricular_activities", input_type: "text" },
    { field_name: "certifications", input_type: "text" },
    { field_name: "university_name", input_type: "text" },
    { field_name: "field_of_study", input_type: "text" },
    { field_name: "gpa_cgpa", input_type: "text" },
    { field_name: "bank_name", input_type: "text" },
    { field_name: "account_type", input_type: "select", options: ["Savings", "Current"] },
    { field_name: "account_number", input_type: "text" },
    { field_name: "ifsc_code", input_type: "text" },
    { field_name: "iban", input_type: "text" },
    { field_name: "branch_name", input_type: "text" },
    { field_name: "account_holder_name", input_type: "text" },
    { field_name: "swift_bic_code", input_type: "text" },
    { field_name: "branch_address", input_type: "text" },
    { field_name: "routing_number", input_type: "text" },
    { field_name: "debit_credit_card_number", input_type: "text" },
    { field_name: "company_name", input_type: "text" },
    { field_name: "job_title", input_type: "text" },
    { field_name: "employment_type", input_type: "select", options: ["Full-time", "Part-time", "Internship"] },
    { field_name: "start_date", input_type: "date" },
    { field_name: "end_date", input_type: "date" },
    { field_name: "salary", input_type: "text" },
    { field_name: "manager_name", input_type: "text" },
    { field_name: "office_location", input_type: "text" },
    { field_name: "job_description", input_type: "text" },
    { field_name: "department", input_type: "text" },
    { field_name: "performance_review", input_type: "text" }
  ];
  
  export default combinedFields;
  